# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lf < Formula
  desc "LayerFlow Terminal (lf) — local-first AI terminal workspace with streaming, tools, memory, and cloud sync."
  homepage "https://github.com/Rohit94r/layerflow-releases"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rohit94r/layerflow-releases/releases/download/v0.2.5/lf_0.2.5_darwin_amd64.tar.gz"
      sha256 "0f06eea6dbc574a423521d91c73834f9145e96928a9908d8d51fe67b1e46f5c9"

      def install
        bin.install "lf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rohit94r/layerflow-releases/releases/download/v0.2.5/lf_0.2.5_darwin_arm64.tar.gz"
      sha256 "1f04ad67c701955c3ee0ff0aff6c039dd79cc00f9ad3ef8952088624abbf2013"

      def install
        bin.install "lf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Rohit94r/layerflow-releases/releases/download/v0.2.5/lf_0.2.5_linux_amd64.tar.gz"
        sha256 "d51b9add1d2e1b5362053ecb2d7932a6bd21777104318618d84d6e1e195de8dc"

        def install
          bin.install "lf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Rohit94r/layerflow-releases/releases/download/v0.2.5/lf_0.2.5_linux_arm64.tar.gz"
        sha256 "9083640236909a9b13fdd16bb6b25e82f15847a948c9c23a27c66599f72842bb"

        def install
          bin.install "lf"
        end
      end
    end
  end

  test do
    assert_match(/LayerFlow/, shell_output("#{bin}/lf version"))
  end
end
